### ISSUE TITLE
/hacsfiles/floor3d-card/floor3d-card.js:2357:4587 Uncaught Error

### ISSUE THREAD

**Issue by yahadzhiev** [adizanni/floor3d-card#148]
Hello, I have a problem, I installed floor3d-card in HACS, the 3D card is new...

Logger: frontend.js.latest.202302020
Source: components/system_log/__init__.py:254
First occurred: 22:15:30 (1 occurrences)
Last logged: 22:15:30

http://192.168.8.13:8123/hacsfiles/floor3d-card/floor3d-card.js:2357:4587 Uncaught Error

```
type: custom:floor3d-card
path: /local/community/floor3d-card/maps/
name: Home
objfile: 1.obj
lock_camera: 'no'
header: 'yes'
click: 'no'
overlay: 'no'
backgroundColor: '#aaaaaa'
hideLevelsMenu: 'no'
globalLightPower: '0.8'
shadow: 'no'
extralightmode: 'no'
show_axes: 'no'
sky: 'no'
overlay_bgcolor: transparent
overlay_fgcolor: black
overlay_alignment: top-left
overlay_width: '33'
overlay_height: '20'
north:
  x: 0
  z: -1
camera_position:
  x: 609.3072605703628
  'y': 905.5330092468828
  z: 376.66437610591277
camera_rotate:
  x: -1.0930244719682243
  'y': 0.5200808414019678
  z: 0.7648717152512469
camera_target:
  x: 37.36890424945437
  'y': 18.64464320782064
  z: -82.55051697031719
object_groups:
  - object_group: RoundTable
    objects:
      - object_id: Round_table_1
      - object_id: Round_table_2
      - object_id: Round_table_3
  - object_group: EntranceDoor
    objects:
      - object_id: Door_9
      - object_id: Door_7
      - object_id: Door_5
entities:
  - entity: binary_sensor.iphone_shamil_focus
    type3d: door
    object_id: <EntranceDoor>
    door:
      doortype: swing
      direction: inner
      hinge: Door_3
      percentage: '90'
  - entity: binary_sensor.sm_x900_is_charging
    type3d: hide
    object_id: <RoundTable>
    hide:
      state: 'off'
zoom_areas:
  - zoom: ''
mtlfile: 1.mtl
```
[](https://nas.muharib.ru/drive/d/s/sQv37HZ6VsWgXi926MGzAivA3bpCDKoR/OdrQ_QsniO-W7app73xducPjULnzQuzl-2Ljgqt7sOQo)
