### ISSUE TITLE
Uncaught error

### ISSUE THREAD

**Issue by shedunraid** [adizanni/floor3d-card#172]
New install of Home Assistant - Core 2023.12.1 - Supervisor 2023.11.6 - Operating System 11.2 - Frontend 20231208.2

The issue only happen when the file exported from SweetHome3d has only 1 room

If i add another room then it will stop this issue from happening

uploaded the test files i was using  - 
office.zip - single room causes the issues bellow
test.zip - added another room - works correctly

[office.zip](https://github.com/adizanni/floor3d-card/files/13654103/office.zip)
[test.zip](https://github.com/adizanni/floor3d-card/files/13654113/test.zip)

Logger: frontend.js.latest.202312082
Source: components/system_log/__init__.py:300
First occurred: 22:58:51 (14 occurrences)
Last logged: 23:11:10

Uncaught error from Safari 16.6 on Mac OS 10.15.7 Error /hacsfiles/floor3d-card/floor3d-card.js:2288:34342 /hacsfiles/floor3d-card/floor3d-card.js:2231:531796 /hacsfiles/floor3d-card/floor3d-card.js:2231:435968
Uncaught error from Safari 16.6 on Mac OS 10.15.7 Error /hacsfiles/floor3d-card/floor3d-card.js:2356:4532 /hacsfiles/floor3d-card/floor3d-card.js:2231:531796 /hacsfiles/floor3d-card/floor3d-card.js:2231:435968
Uncaught error from Chrome 120.0.0.0 on Mac OS 10.15.7 Error /hacsfiles/floor3d-card/floor3d-card.js:2356:4523 Object.onLoad (/hacsfiles/floor3d-card/floor3d-card.js:2231:531795) XMLHttpRequest.<anonymous> (/hacsfiles/floor3d-card/floor3d-card.js:2231:435962)
Uncaught error from Chrome 120.0.0.0 on Mac OS 10.15.7 Error /hacsfiles/floor3d-card/floor3d-card.js:2288:34333 Object.onLoad (/hacsfiles/floor3d-card/floor3d-card.js:2231:531795) XMLHttpRequest.<anonymous> (/hacsfiles/floor3d-card/floor3d-card.js:2231:435962)
Uncaught error from Firefox 120.0 on Mac OS 10.15 Error display3dmodel/< (/hacsfiles/floor3d-card/floor3d-card.js:2288:34333) load/< (/hacsfiles/floor3d-card/floor3d-card.js:2231:531795) load/< (/hacsfiles/floor3d-card/floor3d-card.js:2231:435962)

**Comment by adizanni** [comment]
@shedunraid , I will look into it, even though I can tell you that, rooms are not objects in the model, they are just set of floors, walls, etc. so it should not make a difference if you have 1, 2 or even 0.

**Comment by avishayil** [comment]
Hi, I'm experiencing the same error after updating to the latest home assistant:
````
Core
2023.12.3
Frontend
20231208.2
````
Home Assistant server logs:
````
2023-12-25 09:20:18.702 ERROR (MainThread) [frontend.js.latest.202312082] Uncaught error from Chrome 120.0.0.0 on Mac OS 10.15.7
Error
/hacsfiles/floor3d-card/floor3d-card.js:2356:4523
Object.onLoad (/hacsfiles/floor3d-card/floor3d-card.js:2231:531795)
XMLHttpRequest.<anonymous> (/hacsfiles/floor3d-card/floor3d-card.js:2231:435962)
````
Home Assistant frontend console log:
````
  FLOOR3D-CARD   Version 1.5.3    
floor3d-card.js?hacstag=361776538153:2288 New Card
floor3d-card.js?hacstag=361776538153:2288 floor3d-card: Set Config Start
floor3d-card.js?hacstag=361776538153:2288 floor3d-card: Set Config End
2floor3d-card.js?hacstag=361776538153:2288 Entity <light.kids_room_light> not found
floor3d-card.js?hacstag=361776538153:2288 Entity <fan.kids_room_fan> not found
floor3d-card.js?hacstag=361776538153:2288 First updated start
floor3d-card.js?hacstag=361776538153:2288 Start Build Renderer
floor3d-card.js?hacstag=361776538153:2288 Max Texture Image Units: 16
floor3d-card.js?hacstag=361776538153:2288 Max Texture Image Units: number of lights casting shadow should be less than the above number
floor3d-card.js?hacstag=361776538153:2288 Path: /local/bar-home/
floor3d-card.js?hacstag=361776538153:2288 End Build Renderer
floor3d-card.js?hacstag=361776538153:2288 First updated end
floor3d-card.js?hacstag=361776538153:2356 Material loaded start
floor3d-card.js?hacstag=361776538153:2356 Material loaded end
floor3d-card.js?hacstag=361776538153:2288 Object loaded start
floor3d-card.js?hacstag=361776538153:2288 Ïnit Objects, Levels and Raycasting
floor3d-card.js?hacstag=361776538153:2288 Found level 0
floor3d-card.js?hacstag=361776538153:2288 End Init Objects. Number of levels found: 1
floor3d-card.js?hacstag=361776538153:2288 Shadow Off
floor3d-card.js?hacstag=361776538153:2356 Add Objects Start
4floor3d-card.js?hacstag=361776538153:2356 Create Room
floor3d-card.js?hacstag=361776538153:2356 TypeError: Cannot read properties of undefined (reading 'name')
    at bf._applyTextCanvasSprite (floor3d-card.js?hacstag=361776538153:2356:15475)
    at bf._updateroom (floor3d-card.js?hacstag=361776538153:2356:14112)
    at floor3d-card.js?hacstag=361776538153:2356:11633
    at Array.forEach (<anonymous>)
    at bf._add3dObjects (floor3d-card.js?hacstag=361776538153:2356:11126)
    at bf._onLoaded3DModel (floor3d-card.js?hacstag=361776538153:2288:35635)
    at Object.onLoad (floor3d-card.js?hacstag=361776538153:2231:531770)
    at XMLHttpRequest.<anonymous> (floor3d-card.js?hacstag=361776538153:2231:435962)
floor3d-card.js?hacstag=361776538153:2356 Uncaught Error
    at floor3d-card.js?hacstag=361776538153:2356:4523
    at Object.onLoad (floor3d-card.js?hacstag=361776538153:2231:531795)
    at XMLHttpRequest.<anonymous> (floor3d-card.js?hacstag=361776538153:2231:435962)
(anonymous) @ floor3d-card.js?hacstag=361776538153:2356
(anonymous) @ floor3d-card.js?hacstag=361776538153:2231
(anonymous) @ floor3d-card.js?hacstag=361776538153:2231
load (async)
load @ floor3d-card.js?hacstag=361776538153:2231
load @ floor3d-card.js?hacstag=361776538153:2231
_onLoaded3DMaterials @ floor3d-card.js?hacstag=361776538153:2356
(anonymous) @ floor3d-card.js?hacstag=361776538153:2231
(anonymous) @ floor3d-card.js?hacstag=361776538153:2231
load (async)
load @ floor3d-card.js?hacstag=361776538153:2231
load @ floor3d-card.js?hacstag=361776538153:2231
display3dmodel @ floor3d-card.js?hacstag=361776538153:2288
firstUpdated @ floor3d-card.js?hacstag=361776538153:2288
_$AE @ floor3d-card.js?hacstag=361776538153:11
performUpdate @ floor3d-card.js?hacstag=361776538153:11
scheduleUpdate @ floor3d-card.js?hacstag=361776538153:11
_$Ej @ floor3d-card.js?hacstag=361776538153:11
await in _$Ej (async)
requestUpdate @ floor3d-card.js?hacstag=361776538153:11
u @ floor3d-card.js?hacstag=361776538153:11
b @ floor3d-card.js?hacstag=361776538153:11
lt @ floor3d-card.js?hacstag=361776538153:22
bf @ floor3d-card.js?hacstag=361776538153:2288
C @ scoped-custom-element-registry.js:385
t @ scoped-custom-element-registry.js:236
r @ create-element-base.ts:91
(anonymous) @ create-element-base.ts:109
h @ create-element-base.ts:213
c @ create-element-base.ts:170
f @ create-card-element.ts:101
value @ hui-view.ts:66
value @ hui-view.ts:304
t.addEventListener.once @ hui-view.ts:80
r @ fire_event.ts:76
(anonymous) @ create-element-base.ts:127
Promise.then (async)
(anonymous) @ create-element-base.ts:125
h @ create-element-base.ts:213
c @ create-element-base.ts:170
f @ create-card-element.ts:101
value @ hui-view.ts:66
(anonymous) @ hui-view.ts:288
value @ hui-view.ts:287
value @ hui-view.ts:216
value @ hui-view.ts:132
performUpdate @ reactive-element.ts:1327
scheduleUpdate @ reactive-element.ts:1261
_$Ej @ reactive-element.ts:1233
await in _$Ej (async)
requestUpdate @ reactive-element.ts:1208
_$Eu @ reactive-element.ts:946
_ @ reactive-element.ts:931
i @ hui-view.ts:45
C @ scoped-custom-element-registry.js:385
t @ scoped-custom-element-registry.js:236
value @ hui-root.ts:963
(anonymous) @ hui-root.ts:681
setTimeout (async)
(anonymous) @ render-status.ts:2
requestAnimationFrame (async)
r @ render-status.ts:2
value @ hui-root.ts:681
_$AE @ reactive-element.ts:1378
performUpdate @ reactive-element.ts:1343
scheduleUpdate @ reactive-element.ts:1261
_$Ej @ reactive-element.ts:1233
await in _$Ej (async)
requestUpdate @ reactive-element.ts:1208
_$Eu @ reactive-element.ts:946
_ @ reactive-element.ts:931
A @ lit-element.ts:115
o @ hui-root.ts:103
C @ scoped-custom-element-registry.js:385
t @ scoped-custom-element-registry.js:236
u @ lit-html.ts:1129
g @ lit-html.ts:1543
_$AI @ lit-html.ts:1384
Z @ lit-html.ts:2183
update @ lit-element.ts:165
performUpdate @ reactive-element.ts:1329
scheduleUpdate @ reactive-element.ts:1261
_$Ej @ reactive-element.ts:1233
await in _$Ej (async)
requestUpdate @ reactive-element.ts:1208
set @ reactive-element.ts:726
value @ ha-panel-lovelace.ts:300
await in value (async)
value @ ha-panel-lovelace.ts:167
_$AE @ reactive-element.ts:1376
performUpdate @ reactive-element.ts:1343
scheduleUpdate @ reactive-element.ts:1261
_$Ej @ reactive-element.ts:1233
await in _$Ej (async)
requestUpdate @ reactive-element.ts:1208
_$Eu @ reactive-element.ts:946
_ @ reactive-element.ts:931
A @ lit-element.ts:115
o @ ha-panel-lovelace.ts:54
C @ scoped-custom-element-registry.js:385
t @ scoped-custom-element-registry.js:236
value @ hass-router-page.ts:296
value @ hass-router-page.ts:316
_currentLoadProm.d.then._currentLoadProm @ hass-router-page.ts:214
Promise.then (async)
value @ hass-router-page.ts:205
performUpdate @ reactive-element.ts:1329
scheduleUpdate @ reactive-element.ts:1261
_$Ej @ reactive-element.ts:1233
await in _$Ej (async)
requestUpdate @ reactive-element.ts:1208
set @ reactive-element.ts:726
value @ hass-router-page.ts:284
await in value (async)
value @ partial-panel-resolver.ts:215
value @ partial-panel-resolver.ts:86
performUpdate @ reactive-element.ts:1327
scheduleUpdate @ reactive-element.ts:1261
_$Ej @ reactive-element.ts:1233
await in _$Ej (async)
requestUpdate @ reactive-element.ts:1208
_$Eu @ reactive-element.ts:946
_ @ reactive-element.ts:931
r @ hass-router-page.ts:48
o @ partial-panel-resolver.ts:42
C @ scoped-custom-element-registry.js:385
t @ scoped-custom-element-registry.js:236
u @ lit-html.ts:1129
g @ lit-html.ts:1543
_$AI @ lit-html.ts:1384
Z @ lit-html.ts:2183
update @ lit-element.ts:165
performUpdate @ reactive-element.ts:1329
scheduleUpdate @ reactive-element.ts:1261
_$Ej @ reactive-element.ts:1233
await in _$Ej (async)
requestUpdate @ reactive-element.ts:1208
_$Eu @ reactive-element.ts:946
_ @ reactive-element.ts:931
A @ lit-element.ts:115
s @ home-assistant-main.ts:52
C @ scoped-custom-element-registry.js:385
t @ scoped-custom-element-registry.js:236
u @ lit-html.ts:1129
g @ lit-html.ts:1543
_$AI @ lit-html.ts:1384
Z @ lit-html.ts:2183
update @ lit-element.ts:165
value @ home-assistant.ts:34
performUpdate @ reactive-element.ts:1329
scheduleUpdate @ reactive-element.ts:1261
_$Ej @ reactive-element.ts:1233
await in _$Ej (async)
requestUpdate @ reactive-element.ts:1208
set @ reactive-element.ts:726
value @ hass-base-mixin.ts:56
_updateHass @ context-mixin.ts:95
(anonymous) @ connection-mixin.ts:276
s @ store.js:19
(anonymous) @ collection.js:25
Promise.then (async)
d @ collection.js:25
u @ collection.js:27
(anonymous) @ collection.js:52
subscribe @ collection.js:96
(anonymous) @ frontend.ts:68
(anonymous) @ core.ts:121
Promise.then (async)
(anonymous) @ core.ts:111
(anonymous) @ core.XdmzaKFA4yc.js:1
Show 6 more frames
Show less
````

**Comment by adizanni** [comment]
Hello guys thanks to spot this, I've noticed that a few functions of the card are not working anymore due to changes introduced in the 2023.12.3 release. Something is messed up with DOM elements. I think that it will be tricky to fix, but I'm investigating.....

**Comment by adizanni** [comment]
Hello @shedunraid @avishayil can you post here your yaml card config ?

**Comment by niltrip** [comment]
Hello, i also got these Type of failure. 

At first I thought the error was due to a change I made, but I can't find any error...

```
scheduler-card.js?hacstag=2862701573212:1826   SCHEDULER-CARD    Version: v3.2.12
floor3d-card.js?hacstag=361776538153:2288   FLOOR3D-CARD   Version 1.5.3    
floor3d-card.js?hacstag=361776538153:2288 New Card
floor3d-card.js?hacstag=361776538153:2288 floor3d-card: Set Config Start
floor3d-card.js?hacstag=361776538153:2288 floor3d-card: Set Config End
floor3d-card.js?hacstag=361776538153:2288 Entity <sensor.haus_eg_wc_sensor_temperature> not found
floor3d-card.js?hacstag=361776538153:2288 First updated start
floor3d-card.js?hacstag=361776538153:2288 Start Build Renderer
floor3d-card.js?hacstag=361776538153:2288 Max Texture Image Units: 16
floor3d-card.js?hacstag=361776538153:2288 Max Texture Image Units: number of lights casting shadow should be less than the above number
floor3d-card.js?hacstag=361776538153:2288 Path: /local/Daffingerweg58a/
floor3d-card.js?hacstag=361776538153:2288 End Build Renderer
floor3d-card.js?hacstag=361776538153:2288 First updated end
mini-graph-card-bundle.js?hacstag=1512800620120:1  MINI-GRAPH-CARD  0.12.0 
simple-thermostat.js?hacstag=158654878250:292 simple-thermostat: 2.5.0
myjdownloader-card.js?hacstag=537793361131:55   MyJDownloader-Card   Version 1.2.0
shutter-row.js?hacstag=524783308036:1420 SHUTTER ROW 0.3.6
room-card.js?hacstag=45444094910802:30  ROOM-CARD  1.08.02
mushroom.js?hacstag=444350375330:3651 🍄 Mushroom 🍄 - 3.4.0
energy-flow-card-plus.js?hacstag=6382302440121:1 ⚡ Energy Flow Card Plus v0.1.2.1 is installed
hass-hue-icons.js?hacstag=3844345221253:2074  HASS-HUE-ICONS  Version 1.2.53 
power-flow-card-plus.js?hacstag=6180818150181:1 ⚡ Power Flow Card Plus v0.1.8.1 is installed
weather-radar-card.js?hacstag=487680971210:1291   WEATHER-RADAR-CARD   Version 2.1.0    
floor3d-card.js?hacstag=361776538153:2288 Object loaded start
floor3d-card.js?hacstag=361776538153:2288 Ïnit Objects, Levels and Raycasting
floor3d-card.js?hacstag=361776538153:2288 Found level 0
floor3d-card.js?hacstag=361776538153:2288 Found level 001
floor3d-card.js?hacstag=361776538153:2288 Found level 004
floor3d-card.js?hacstag=361776538153:2288 Found level 007
floor3d-card.js?hacstag=361776538153:2288 Found level 009
floor3d-card.js?hacstag=361776538153:2288 End Init Objects. Number of levels found: 10
floor3d-card.js?hacstag=361776538153:2288 Shadow On
floor3d-card.js?hacstag=361776538153:2356 Add Objects Start
floor3d-card.js?hacstag=361776538153:2356 Create Room
floor3d-card.js?hacstag=361776538153:2356 Create Room
floor3d-card.js?hacstag=361776538153:2356 Create Room
floor3d-card.js?hacstag=361776538153:2356 Create Room
floor3d-card.js?hacstag=361776538153:2356 Create Room
floor3d-card.js?hacstag=361776538153:2356 TypeError: Cannot read properties of undefined (reading 'name')
    at bf._applyTextCanvasSprite (floor3d-card.js?hacstag=361776538153:2356:15475)
    at bf._updateroom (floor3d-card.js?hacstag=361776538153:2356:14112)
    at floor3d-card.js?hacstag=361776538153:2356:11633
    at Array.forEach (<anonymous>)
    at bf._add3dObjects (floor3d-card.js?hacstag=361776538153:2356:11126)
    at bf._onLoaded3DModel (floor3d-card.js?hacstag=361776538153:2288:35635)
    at bf._onLoadedGLTF3DModel (floor3d-card.js?hacstag=361776538153:2288:34978)
    at floor3d-card.js?hacstag=361776538153:2231:540195
    at floor3d-card.js?hacstag=361776538153:2231:559625
floor3d-card.js?hacstag=361776538153:2356 Uncaught (in promise) Error: Error adding 3D Object: TypeError: Cannot read properties of undefined (reading 'name')
    at bf._add3dObjects (floor3d-card.js?hacstag=361776538153:2356:11768)
    at bf._onLoaded3DModel (floor3d-card.js?hacstag=361776538153:2288:35635)
    at bf._onLoadedGLTF3DModel (floor3d-card.js?hacstag=361776538153:2288:34978)
    at floor3d-card.js?hacstag=361776538153:2231:540195
    at floor3d-card.js?hacstag=361776538153:2231:559625
_add3dObjects @ floor3d-card.js?hacstag=361776538153:2356
_onLoaded3DModel @ floor3d-card.js?hacstag=361776538153:2288
_onLoadedGLTF3DModel @ floor3d-card.js?hacstag=361776538153:2288
(anonymous) @ floor3d-card.js?hacstag=361776538153:2231
(anonymous) @ floor3d-card.js?hacstag=361776538153:2231
Promise.then (async)
(anonymous) @ floor3d-card.js?hacstag=361776538153:2231

```


Thanks.

**Comment by adizanni** [comment]
Can you post your Yaml config ?

**Comment by niltrip** [comment]
```
type: custom:floor3d-card
name: Haus
path: /local/Haus/
objfile: home.glb
mtlfile: home.mtl
objectlist: home.json
lock_camera: 'no'
header: 'yes'
click: 'yes'
overlay: 'yes'
globalLightPower: '0.3'
shadow: 'yes'
extralightmode: 'yes'
show_axes: 'no'
sky: 'yes'
backgroundColor: '#000000'
hideLevelsMenu: 'no'
zoom_areas:
  - zoom: ''
selectionMode: 'no'
north:
  x: 0.707
  'y': 0
  z: -0.707
camera_position:
  x: 289.9753805216309
  'y': 678.9836309806486
  z: 1546.2361101007639
camera_rotate:
  x: -0.29659895179527235
  'y': 0.25690896685642567
  z: 0.07749851667337507
camera_target:
  x: 0
  'y': 0
  z: 0
entities:
  - entity: light.haus_eg_wz_licht_switch_1
    type3d: light
    object_id: living_room_light_01_2
    light:
      lumens: 500
      shadow: 'yes'
      vertical_alignment: top
    action: default
  - entity: light.haus_eg_wz_licht_essbereich_switch_0
    type3d: light
    object_id: living_room_light_02_2
    light:
      lumens: 800
      shadow: 'yes'
    action: overlay
  - entity: light.stehlampe_wohnzimmer
    type3d: light
    object_id: Stehlampe_2
    light:
      lumens: 500
      shadow: 'yes'
      vertical_alignment: top
    action: default
  - entity: cover.shellyplus2pm_b8d61a894e50
    type3d: hide
    object_id: living_room_window_02_24
    hide:
      state: open
  - entity: light.haus_eg_gz_licht_switch_0
    type3d: light
    object_id: guest_room_light_01_2
    light:
      lumens: 800
      shadow: 'yes'
  - entity: light.haus_eg_k_licht_switch_0
    type3d: light
    object_id: kitchen_light_01_2
    light:
      lumens: 800
      shadow: 'yes'
  - entity: light.haus_eg_k_licht_switch_1
    type3d: light
    object_id: <light_kitchen_work>
    light:
      lumens: 400
      shadow: 'yes'
  - entity: light.haus_og_kz1_licht_switch_0
    type3d: light
    object_id: child_room_01_light_1
    light:
      lumens: 4000
      shadow: 'yes'
  - entity: light.haus_og_kz2_licht_switch_0
    type3d: light
    object_id: child_room_02_light_1
    light:
      lumens: 4000
      shadow: 'yes'
  - entity: cover.haus_og_sz_rolladen_nord
    type3d: hide
    object_id: bedroom_window_02_18
    hide:
      state: 'on'
  - entity: light.haus_og_sz_licht_switch_0
    type3d: light
    object_id: bedroom_light_01_2
    light:
      lumens: 800
      shadow: 'yes'
  - entity: light.haus_og_sz_licht_schrank_switch_0
    type3d: light
    object_id: bedroom_light_02_2
    light:
      lumens: 800
      shadow: 'yes'
  - entity: sensor.rhsensor_06_temperature
    type3d: room
    object_id: room_7_1
    room:
      transparency: 100
      label: 'yes'
      span: 50
      font: arial
      textbgcolor: black
      textfgcolor: white
      label_text: template
  - entity: light.haus_eg_wc_licht_switch_0
    type3d: light
    object_id: guest_toilet_light_01_2
    light:
      lumens: 800
      shadow: 'yes'
  - entity: light.haus_eg_hwr_licht_switch_0
    type3d: light
    object_id: house_utility_room_light_2
    light:
      lumens: 800
      shadow: 'yes'
  - entity: light.haus_og_bz_licht_switch_0
    type3d: light
    object_id: <light_bathroom>
    light:
      lumens: 400
      shadow: 'yes'
  - entity: light.lampe_01
    type3d: light
    object_id: attic_light_01_1
    light:
      lumens: 800
      shadow: 'yes'
  - entity: sensor.haus_eg_wc_sensor_temperature
    type3d: room
    object_id: room_1_1
    room:
      transparency: 100
      label: 'yes'
      span: 50
      font: arial
      textbgcolor: black
      textfgcolor: white
      label_text: template
  - entity: sensor.rhsensor_04_temperature
    type3d: room
    object_id: room_2_1
    room:
      transparency: 100
      label: 'yes'
      span: 50
      font: arial
      textbgcolor: black
      textfgcolor: white
      label_text: template
  - entity: sensor.haus_og_sz_sensor_ht_temperature
    type3d: room
    object_id: room_10_1
    room:
      transparency: 100
      label: 'yes'
      span: 50
      font: arial
      textbgcolor: black
      textfgcolor: white
      label_text: template
  - entity: sensor.rhsensor_05_temperature
    type3d: room
    object_id: room_0_1
    room:
      transparency: 100
      label: 'yes'
      span: 50
      font: arial
      textbgcolor: black
      textfgcolor: white
      label_text: template
  - entity: light.haus_eg_f_licht_switch_0
    type3d: light
    object_id: hall_01_light_01_1
    light:
      lumens: 1000
      shadow: 'yes'
  - entity: light.haus_og_ga_licht_switch_0
    type3d: light
    object_id: hall_02_light_1
    light:
      lumens: 800
      shadow: 'yes'
  - entity: sensor.rhsensor_02_temperature
    type3d: room
    object_id: room_9_1
    room:
      transparency: 100
      label: 'yes'
      span: 50
      font: arial
      textbgcolor: black
      textfgcolor: white
      label_text: template
  - entity: sensor.haus_og_bz_sensor_ht_temperature
    type3d: room
    object_id: room_5_1
    room:
      transparency: 100
      label: 'yes'
      span: 50
      font: arial
      textbgcolor: black
      textfgcolor: white
      label_text: template
  - entity: sensor.rhsensor_03_temperature
    type3d: room
    object_id: room_4_1
    room:
      transparency: 100
      label: 'yes'
      span: 50
      font: arial
      textbgcolor: black
      textfgcolor: white
      label_text: template
  - entity: sensor.rhsensor_01_temperature
    type3d: room
    object_id: room_3_1
    room:
      transparency: 100
      label: 'yes'
      span: 50
      font: arial
      textbgcolor: black
      textfgcolor: white
      label_text: template
  - entity: cover.shellyplus2pm_441793abe7bc
    type3d: cover
    object_id: <roller_shutter_guest_room>
    cover:
      pane: guest_room_window_9
      side: up
  - entity: binary_sensor.bewegungsmelder_01_occupancy
    type3d: color
    object_id: room_0_1
    colorcondition:
      - state: 'on'
        color: '#FFC107'
  - entity: media_player.samsung
    type3d: color
    object_id: Wandflachbildschirm_3
    colorcondition:
      - state: 'on'
        color: blue
      - state: 'off'
        color: black
    action: more-info
object_groups:
  - object_group: light_bathroom
    objects:
      - object_id: bathroom_spotlight_01_1
      - object_id: bathroom_spotlight_02_1
      - object_id: bathroom_spotlight_03_1
      - object_id: bathroom_spotlight_04_1
      - object_id: bathroom_spotlight_05_1
      - object_id: bathroom_spotlight_06_1
      - object_id: bathroom_spotlight_07_1
  - object_group: light_kitchen_work
    objects:
      - object_id: kitchen_light_02_1
      - object_id: kitchen_light_03_1
      - object_id: kitchen_light_04_1
  - object_group: roller_shutter_guest_room
    objects:
      - object_id: guest_room_window_18
      - object_id: guest_room_window_19
```
