### ISSUE TITLE
Numerical Object Id is not being accepted

### ISSUE THREAD

**Issue by sheminasalam** [adizanni/floor3d-card#20]
I have the latest version of this card. The following is one of the entity config.
```
      - entity: switch.thashin_g1c
        type3d: hide
        object_id: 668
        hide:
          state: 'off'
```
Since the object id is just a 3 digit number I get the following error.
``` n.object_id.charAt is not a function ```

**Comment by adizanni** [comment]
Have you tried to wrap the object_id into quotes like this:

```yaml
 - entity: switch.thashin_g1c
        type3d: hide
        object_id: '668'
        hide:
          state: 'off'
```

I have also a numeric object but I have no problem as it is treated as a string
