### ISSUE TITLE
Double click on object  A and light on/off on object B.

### ISSUE THREAD

**Issue by uspass** [adizanni/floor3d-card#40]
**Is your feature request related to a problem? Please describe.**
Double click on object  A and light on/off on object B.

**Describe the solution you'd like**
Double click on object  A and light on/off on object B.

**Describe alternatives you've considered**
None.

**Additional context**
None.

**Comment by adizanni** [comment]
Hello uspass, this is already possible thanks to the Gesture (I know the name is not good) entity type.
You can define an entity A associated to an object B and execute service DOMAIN.SERVICE on the entity when you click on the object B. Please try and tell me if it is what you asked for

**Comment by uspass** [comment]
Hi Andy,
Yes, that works:
```
         - entity: light.an_entity
            type3d: light
            object_id: objectB_it_lights
            light:
              lumens: '250'
        - entity: light.an_entity
            type3d: gesture
            object_id: objectA_double_clicked
            gesture:
              domain: light
              service: toggle
```
Double click on **objectA_double_clicked** toggle light on **objectB_it_lights**

Thanks,
us
