### ISSUE TITLE
Swing window in wrong position

### ISSUE THREAD

**Issue by uspass** [adizanni/floor3d-card#42]
**Checklist:**

- [x ] I updated to the latest version available
- [ x] I cleared the cache of my browser

**Release with the issue:**
1.0.1 Alfa
**Last working release (if known):**

**Browser and Operating System:**
Any browser windows 10

**Description of problem:**
```
          - entity: binary_sensor.sensor_window_1
            type3d: door
            object_id: Window1
            door:
              doortype: swing
              side: right
              direction: outer
```

Swing window in wrong position for right and outer.

![Window](https://user-images.githubusercontent.com/42880649/130404102-08d69fd0-a387-4b7d-970a-a013d47fd57a.png)

The other 3 combinations work (right/inner, left/outer and left/inner).
NB. In my case inner and outer are the other way around inner is outside and outer is inside.

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**
