### ISSUE TITLE
type in instructions

### ISSUE THREAD

**Issue by ikrowni** [adizanni/floor3d-card#51]
Typo in the instructions page. For the SHOW section you have this snippet

```
entities
  - entity: <a binary sensor entity id>
    type3d: hide
    object_id: <an object_id in the model you want to hide if condition is true>
    show:
      state: <the state of the entity triggering the showing of the object: ex 'off'>
```

the type3d: is incorrect and should be show instead of hide
