### ISSUE TITLE
Color and text types can't be used simultaneously on the same object_id

### ISSUE THREAD

**Issue by uspass** [adizanni/floor3d-card#56]
**Checklist:**

- [x] I updated to the latest version available
- [x] I cleared the cache of my browser

**Release with the issue:**
v1.1.1
**Last working release (if known):**
None
**Browser and Operating System:**
Any
Windows 10

**Description of problem:**
Say one has the following configuration:

```
          - entity: sensor.climate_living_hvac_mode
            type3d: color
            object_id: LivingTemperature
            colorcondition:
              - state: 'cool'
                color: '#D4F3FF'
              - state: 'heat'
                color: '#FFBDBB'
              - state: 'off'
                color: '#FFFFFF'
              - state: 'fan_only'
                color: '#B5FFC1'
          - entity: sensor.climate_living_temperature
            type3d: text
            object_id: LivingTemperature
            text:
              span: 50%
              font: Arial
              textfgcolor: black
              textbgcolor: white
```
Floor3D does the background color set in the first entity and overwrites everything with the background color (black) in the second entity. If change order of the entities then the text is not shown at all (only the background color set in the color condition).
Possible solutions: Either have transparent background to text type or color condition to the text type background (as in color type) related to a different entity.

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**
