### ISSUE TITLE
Using sensor 'attributes'

### ISSUE THREAD

**Issue by wishie** [adizanni/floor3d-card#59]
I wish to be able to use an attribute of a sensor entity for the 'text' type..

I have a climate.air_con entity, and I wish to display its 'current_temperature' attribute on the wall in my 3D model. I can not see a way to access 'current_temperature' using your card. I am aware I could make a template sensor for this, but I believe it's overkill.

Can you provide a way to specify which attributes to use?

**Comment by jli113** [comment]
Live data representation +1

**Comment by adizanni** [comment]
Added support for the 'attribute' parameter for the text entity, In future releases, I will try to promote it to the entity level to make it work for all other entity types where it make sense

**Comment by jli113** [comment]
Does it work like this: 
type: custom:floor3d-card
entities:
  - entity: sensor.lywsd03mmc_humidity_1
    type3d: text
    text:
      font: '100'
      textbgcolor: blue
      textfgcolor: yellow
      attribute: sensor.lywsd03mmc_humidity_1
    object_id: wall_11_64
object_groups:
  - object_group: ''
name: Sample
path: /local/home/
objfile: userGuideExample.obj
mtlfile: userGuideExample.mtl
The temperature sensor has data but the model only shows color.
![image](https://user-images.githubusercontent.com/33822210/141284850-91eb60e5-df3a-4288-aba8-51da9e729f4d.png)
![image](https://user-images.githubusercontent.com/33822210/141284901-e8a14303-2198-48e8-a824-4587f6c4e8a3.png)

**Comment by adizanni** [comment]
In the attribute parameter, you should put the name of the attribute you want to show not the name of the entity. As an exmple if you put a light entity called light.lvinig in the attribute you can put something like 'brightness'

**Comment by jli113** [comment]
> In the attribute parameter, you should put the name of the attribute you want to show not the name of the entity. As an exmple if you put a light entity called light.lvinig in the attribute you can put something like 'brightness'

 Even so, it is only showing Black color.
![image](https://user-images.githubusercontent.com/33822210/141404912-7c9ad131-36b7-4fed-8c52-b0c50b913cea.png)

**Comment by adizanni** [comment]
Is atttibute "Power" (capital p) or power. The impression is that it does not find the attribute. Also the text is better suited for plane objects. I've never tested it in no plane objects

**Comment by uspass** [comment]
@wishie 

If you want to get something like this

![temp](https://user-images.githubusercontent.com/42880649/141655773-b8c787d1-f92d-48b4-9a8c-6b4c703098cf.png)

I can share you the way I've done it.

Cheers,
us

**Comment by adizanni** [comment]
There was a bug in the version I've loaded, nevertheless the text entities should be applied to plane objects (frames, tvs, laptop screens, walls, etc.) the result on curved object is unpredictable.

**Comment by adizanni** [comment]
Please test the behaviour in v1.1.5 (new), but please avoid the use of non-plane objects for the text entity

**Comment by jli113** [comment]
Turns out that I didn't set attributes in the ESPhome device entity.

**Comment by adizanni** [comment]
So is it now working as expected ? Can we close the issue ?

**Comment by jli113** [comment]
@uspass 
I'm totally interested, can you please share how you make it?

**Comment by Luke888888** [comment]
Sorry for breaking into the thread.

In version 1.1.5 I can confirm this is working.

### With pure sensor data
```
  - entity: sensor.car_soc
    type3d: text
    object_id: Box_Car1_Charge_2
    text:
      textfgcolor: black
```
![image](https://user-images.githubusercontent.com/14823801/141794283-ea853b32-c965-4898-94d8-5db543cad07b.png)

### With attribute
```
  - entity: climate.entre
    type3d: text
    object_id: Box_Car1_Charge_2
    text:
      textfgcolor: black
      attribute: current_temperature
```
![image](https://user-images.githubusercontent.com/14823801/141794186-2f9e3ed5-37fc-4394-8200-2dfb53392ec8.png)

### With template
```
  - entity: sensor.car_soc
    type3d: text
    object_id: Box_Car1_Charge_2
    entity_template: '[[[ if ($entity > 50) { "OK" } else { "Charge me" } ]]]'
    text:
      textfgcolor: black
```
![image](https://user-images.githubusercontent.com/14823801/141794037-39e2e0d0-64c9-441f-968c-50f05559e9b3.png)
