### ISSUE TITLE
Double click don't work

### ISSUE THREAD

**Issue by Umarkhabiliy** [adizanni/floor3d-card#74]
does not light up when pressed on an object?

**Comment by adizanni** [comment]
Hello @Umarkhabiliy, I'm really sorry but I cannot help. In my model it is working fine. If you do not see errors in the console and the light is visible when you switch it on from home assistant, then I really do not know what is going on

**Comment by adizanni** [comment]
hello @Umarkhabiliy, this example works for me. 1 light, double click works

```yaml
type: custom:floor3d-card
entities:
  - entity: switch.plug_parent_room_on_off
    type3d: light
    object_id: LampMBR_2
    light:
      lumens: '500'
      shadow: 'yes'
      vertical_alignment: top
object_groups:
  - object_group: ''
path: /local/home/
objfile: home.obj?ver=1
mtlfile: home.mtl?ver=1
name: 'New Home '
shadow: 'yes'
```
