### ISSUE TITLE
adding more than 3 entities gone crazy

### ISSUE THREAD

**Issue by aymanokail** [adizanni/floor3d-card#79]
-  I updated to the latest version available
-  I cleared the cache of my browser

i have installed this card and it is working smoothly and actually it is a great option for that i was looking for from long time.

i just have a problem, when i add 3 entities and assigned each entity to object or object group its working fine, but if i add any 4th entity and assigned it to any object the 3d card miss behave, which means many items of my 3D model disappear and all the textures disappear also.

you can see below photos before and after adding a 4th entity

Before
![1](https://user-images.githubusercontent.com/64815121/152371504-69a486b0-a108-4790-afc0-0931d283c364.png)

After
![2](https://user-images.githubusercontent.com/64815121/152371567-ca267c75-a314-44c3-aa9b-b095dc53c778.png)

and this is the code i did

```
 - title: DIG TWIN
    path: dig-twin
    type: panel
    badges: []
    cards:
      - type: custom:floor3d-card
        entities:
          - entity: light.bedroom_light
            type3d: light
            object_id: bedroom_light_2
            action: default
            light:
              lumens: '300'
              vertical_alignment: bottom
              shadow: 'yes'
          - entity: light.mirror_light
            object_id: <mirror_light>
            type3d: light
            action: default
            light:
              lumens: '50'
              shadow: 'yes'
              vertical_alignment: bottom
          - entity: light.dining_light
            action: default
            type3d: light
            object_id: <dining>
            light:
              lumens: '100'
              shadow: 'yes'
              vertical_alignment: bottom
        object_groups:
          - object_group: mirror_light
            objects:
              - object_id: mirror_light_6
              - object_id: mirror_light_4
              - object_id: mirror_light_7
              - object_id: mirror_light_1
              - object_id: mirror_light_9
              - object_id: mirror2_light_4
              - object_id: mirror2_light_6
              - object_id: mirror2_light_1
          - object_group: dining
            objects:
              - object_id: dinning_light_2
              - object_id: dinning_light_4
              - object_id: dinning_light_3
              - object_id: dinning2_light_2
              - object_id: dinning2_light_4
              - object_id: dinning2_light_3
        name: Dig Twin
        path: /local/dt3/
        objfile: home.obj
        mtlfile: home.mtl
        shadow: 'yes'
        camera_position:
          x: 554.6902571341334
          'y': 2201.435041384035
          z: 43.748093828484706
        camera_rotate:
          x: -1.5682508817496652
          'y': 0.14879129458722073
          z: 1.5536272037980616
        camera_target:
          x: 209.6918371025691
          'y': -100.09469514118388
          z: 37.889663711365195
        click: 'yes'
        objectlist: home.json
```

please help to solve this issue
