### ISSUE TITLE
Light sources for downlights

### ISSUE THREAD

**Issue by gcorgnet** [adizanni/floor3d-card#84]
**Checklist:**

- [x ] I updated to the latest version available
- [x ] I cleared the cache of my browser

**Release with the issue:**
1.3.2
**Last working release (if known):**

**Browser and Operating System:**
Windows / Chrome

**Description of problem:**

I have groups of lights in my 3d Model (see screenshot) that don't seem to be exported (eg I can't see any reference to them in my *.obj or *.json files.
There are represented by multiple "White Light Sources"

![image](https://user-images.githubusercontent.com/4731735/156106459-3868e85f-d82c-48f2-9823-5bd96ce38c5b.png)

These are simulating downlights on the ceiling and are not visible on the 3d model (appart from providing light)
What's the best approach for this?

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Comment by adizanni** [comment]
Hello @gcorgnet, light sources are not exported to obj. Best is to create a light object (ex a small cube in order not to change the visible scene) in the same position as the light source and bind that object to the light entity.

**Comment by gcorgnet** [comment]
Makes sense, thanks. How will your plugin know to turn on/off the light source though?

**Comment by adizanni** [comment]
When you import the model in the Card you will be able to bind the light entity to the object you have created in place of the light sources. The light will be sitched on and off based on the state of the light entity. Also if you double-click on the object you toggle the light. I've seen people doing small cylinders like spot light as light source, they are nice and they can easily be double clicked to toggle the light.

**Comment by adizanni** [comment]
The cylinder becomes the light source once you bind it with the light entity in HA with this config:

```yaml
entity: light.ight1
object_id: cylinder1
light:
  lumens:.... etc
```

**Comment by gcorgnet** [comment]
I see, thanks.
Last thing. My light entity in HA is a Phillips Hue group (essentially 2x lightbulbs that are turned off and on as one)
What's the best way of representing this? Would still ike to have 2x downlight objects (eg cylinders) in my 3D map. How would I pair this up with a single HA entity?
Thanks

**Comment by adizanni** [comment]
You can achieve that in either of two ways:

1. By assigning twice the same light group to two different objects:
```yaml
entity: light.group1
object_id: cylinder1
light:
  lumens:.... etc
entity: light.group1
object_id: cylinder2
light:
  lumens:.... etc
```

2. with an object group

```yaml
entity: light.group1
object_id: <lightgroup1>
light:
  lumens:.... etc
object_groups:
  - object_group: lightgroup1
    objects:
      - object_id: cylinder1
      - object_id: cylinder2 
```

They are perfectly equivalent
