### ISSUE TITLE
Error adding project

### ISSUE THREAD

**Issue by syndikatss** [adizanni/floor3d-card#95]
Everything worked well until I decided to make another window in home assiatnt and create another project there. Now, not in the old, not in the new, projects are not loaded.

Logger: frontend.js.latest.202203012
Source: components/system_log/__init__.py:190
First occurred: 16:29:47 (2 occurrences)
Last logged: 16:29:51

http://192.168.31.45:8123/hacsfiles/floor3d-card/floor3d-card.js?hacstag=3617765381412:2311:3870 Uncaught Error

**Comment by adizanni** [comment]
Please send the configuration of the second project, the one that broke everything. Thanks

**Comment by syndikatss** [comment]
Unfortunately, that configuration is gone, but I just tried to add a new project there, set the path to the obj and mtl files, and that's it. But I tried to delete all existing plans and add again, I also tried to create a new plan in sweet home with literally one room and some furniture, the result is the same. I also have a browser and used the phone. I even downgraded the component and opened HA, always the same error (finished with errors: check the console log). Your standard plan is displayed without problems. Perhaps somewhere the sentences look complicated, I write with the help of a translator.

**Comment by Kretiandpleti** [comment]
I´m experiencing the exact same issue. I tried your script for the first time a couple of days ago, but I never made it fly. I tried earlier version with the same issue. 

http://homeassistant.local:8123/local/community/floor3d-card/floor3d-card.js:2311:3870 Uncaught Error
http://homeassistant.local:8123/config/lovelace/resources:0:0 Uncaught
http://homeassistant.local:8123/hacsfiles/floor3d-card/floor3d-card.js?hacstag=3617765381412:2311:3870 Uncaught Error
http://homeassistant.local:8123/hacsfiles/floor3d-card/floor3d-card.js?hacstag=3617765381412:2262:15836 Uncaught TypeError: Cannot read properties of undefined (reading 'removeEventListener')

**Comment by adizanni** [comment]
@Kretiandpleti which script are you talking about ? the ExportToHASS plugin ?

**Comment by syndikatss** [comment]
> So it is possible that your model is containing some elements that are not read correctly by the card. Is there a way you can send the sh3d file to me ?

I can send you my file, but the fact is that even old projects that I did not change do not work. I don’t understand why, but now none of them work after that one failure
[12.zip](https://github.com/adizanni/floor3d-card/files/8458585/12.zip)

**Comment by hxy2019** [comment]
Excuse me
please help me
hacsfiles/floor3d-card/floor3d-card.js?hacstag=3617765381412:2311:3876 Error:
/hacsfiles/floor3d-card/floor3d-card.js?hacstag=3617765381412:2262:15821 TypeError: this._controls is undefined
/hacsfiles/floor3d-card/floor3d-card.js?hacstag=3617765381412:2311:3870 Uncaught Error
/hacsfiles/floor3d-card/floor3d-card.js?hacstag=3617765381412:2262:31468 Uncaught Error
/hacsfiles/floor3d-card/floor3d-card.js?hacstag=3617765381412:2262:15836 Uncaught TypeError: Cannot read properties of undefined (reading 'removeEventListener')

**Comment by hxy2019** [comment]
[Uploading qiangti.zip…]()

**Comment by adizanni** [comment]
Hello @hxy2019 , the link above is just a github URL pointing to this issue

**Comment by adizanni** [comment]
Hello @hxy2019, I give it a try, the error is odd, can you please share your card config too.

**Comment by hxy2019** [comment]
@adizanni  hi ，  I just changed the path and the filename
![QQ截图20220420091202](https://user-images.githubusercontent.com/42147214/164127578-9071394b-ac1a-4092-a7b3-d8867bc314e4.jpeg)

**Comment by adizanni** [comment]
@hxy2019, and is it working now ?

**Comment by hxy2019** [comment]
@adizanni  show "Finished with errors: check the console log"

**Comment by adizanni** [comment]
Ok, so with the card editor opened, please click on "show code editor" in the bottom left, copy the code and paste it in a message here. Thanks

**Comment by hxy2019** [comment]
@adizanni 
type: custom:floor3d-card
path: /local/community/floor3d-card/home414/
name: Home
objfile: home.obj
shadow: 'yes'
globalLightPower: '0.8'
header: 'no'
camera_position:
  x: 609.3072605703628
  'y': 905.5330092468828
  z: 376.66437610591277
camera_rotate:
  x: -1.0930244719682243
  'y': 0.5200808414019678
  z: 0.7648717152512469
camera_target:
  x: 37.36890424945437
  'y': 18.64464320782064
  z: -82.55051697031719
object_groups:
  - object_group: RoundTable
    objects:
      - object_id: Round_table_1
      - object_id: Round_table_2
      - object_id: Round_table_3
  - object_group: EntranceDoor
    objects:
      - object_id: Door_9
      - object_id: Door_7
      - object_id: Door_5
entities:
  - entity: binary_sensor.mi_10_interactive
    type3d: door
    object_id: <EntranceDoor>
    door:
      doortype: swing
      direction: inner
      hinge: Door_3
      percentage: '90'
  - entity: binary_sensor.mi_10_is_charging
    type3d: hide
    object_id: <RoundTable>
    hide:
      state: 'off'
  - entity: light.sonoff_10013ee629_1
    type3d: light
    object_id: Bowl_2
    light:
      lumens: '800'
zoom_areas:
  - zoom: ''
mtlfile: home.mtl

**Comment by hxy2019** [comment]
@adizanni 

`type: custom:floor3d-card
path: /local/community/floor3d-card/home414/
name: Home
objfile: home.obj
shadow: 'yes'
globalLightPower: '0.8'
header: 'no'
camera_position:
  x: 609.3072605703628
  'y': 905.5330092468828
  z: 376.66437610591277
camera_rotate:
  x: -1.0930244719682243
  'y': 0.5200808414019678
  z: 0.7648717152512469
camera_target:
  x: 37.36890424945437
  'y': 18.64464320782064
  z: -82.55051697031719
object_groups:
  - object_group: RoundTable
    objects:
      - object_id: Round_table_1
      - object_id: Round_table_2
      - object_id: Round_table_3
  - object_group: EntranceDoor
    objects:
      - object_id: Door_9
      - object_id: Door_7
      - object_id: Door_5
entities:
  - entity: binary_sensor.mi_10_interactive
    type3d: door
    object_id: <EntranceDoor>
    door:
      doortype: swing
      direction: inner
      hinge: Door_3
      percentage: '90'
  - entity: binary_sensor.mi_10_is_charging
    type3d: hide
    object_id: <RoundTable>
    hide:
      state: 'off'
  - entity: light.sonoff_10013ee629_1
    type3d: light
    object_id: Bowl_2
    light:
      lumens: '800'
zoom_areas:
  - zoom: ''
mtlfile: home.mtl
`

**Comment by adizanni** [comment]
Please using the visual editor try to perform the suggested actions

```yaml
type: custom:floor3d-card
path: /local/community/floor3d-card/home414/    <----- models can be put in all folders under /local/.... (cooresponding to /config/www/ folder). You are using the location of the sample which will work but the model my be overridden by HACS
name: Home
objfile: home.obj
shadow: 'yes'
globalLightPower: '0.8'
header: 'no'
camera_position:
  x: 609.3072605703628
  'y': 905.5330092468828
  z: 376.66437610591277
camera_rotate:
  x: -1.0930244719682243
  'y': 0.5200808414019678
  z: 0.7648717152512469
camera_target:
  x: 37.36890424945437
  'y': 18.64464320782064 
  z: -82.55051697031719
object_groups:
  - object_group: RoundTable    <----- Remove the object Groups, they are coming from the sample
    objects:
      - object_id: Round_table_1
      - object_id: Round_table_2
      - object_id: Round_table_3
   - object_group: EntranceDoor <----- Remove the object Groups, they are coming from the sample
     objects:
       - object_id: Door_9
       - object_id: Door_7
       - object_id: Door_5
entities:
  - entity: binary_sensor.mi_10_interactive
     type3d: door
     object_id:    <---- you always need to put an object name (id), in the case of a door this is the group of objects that are moving in a door
     door:
       doortype: swing
       direction: inner
       hinge: Door_3
       percentage: '90'
  - entity: binary_sensor.mi_10_is_charging
     type3d: hide
     object_id: <------- you always need to put an object name (id), in the case of the hide, it is the object that you want to hide when the state of the entity is off
     hide:
       state: 'off'
   - entity: light.sonoff_10013ee629_1
      type3d: light
      object_id: Bowl_2 <----- this is the object name in the example, you need to replace it with a light object from your model
      light:
        lumens: '800'
zoom_areas:
zoom: ''
mtlfile: home.mtl
```

**Comment by hxy2019** [comment]
@adizanni  thank you

**Comment by adizanni** [comment]
Start from the basics with this configuration and then you add things:

```yaml
type: custom:floor3d-card
path: /local/home414/    <----- move the model folder to the /config/www/ folder
name: Home
objfile: home.obj
shadow: 'yes'
globalLightPower: '0.8'
header: 'no'
mtlfile: home.mtl
```
