### ISSUE TITLE
The Card Suddenly Crashes

### ISSUE THREAD

**Issue by VITCHEPF** [adizanni/floor3d-card#96]
**Checklist:**

- [X ] I updated to the latest version available
- [ ] I cleared the cache of my browser

**Release with the issue:**
floor3d-card V.1.4.1-hf2

**Last working release (if known):**

**Browser and Operating System:**
Chrome - Versão 99.0.4844.84 (Versão oficial) 64 bits

Windows 10 Pro - 21H2

CPU - Intel(R) Core(TM) i7-10700F CPU @ 2.90GHz   2.90 GHz
RAM MEMORY: 16GB
VIDEO CARD: AMD Radeon HD 6700 Series

**Description of problem:**

Suddenly the card started to freeze, not accepting commands for movements and not rendering anymore.

I realize that if I remove the command "Shadow: yes" the processing became "lighter" and work a litle bit more, but even so, sometimes it crashes suddenly.

I'm using a simple test 3D model, which previously worked perfectly, but after the updates below the problems started.

I cleared the CACHE many times.

It's as if the routine entered in a continuous loop, not processing the other commands.

The current versions I'm using of HA and Floor3d-Card are:

![Versão do HA](https://user-images.githubusercontent.com/73760504/162111524-d1b16fcc-fa8c-4169-aa0a-ab3a82b92510.jpg)

**Javascript errors shown in the web inspector (if applicable):**

```

```

**Additional information:**

**Please, see below the simple code used:**

```
type: custom:floor3d-card
name: TEST
path: \local\test\
objfile: home.obj
mtlfile: home.mtl
backgroundColor: Black
camera_position:
  x: 24.59222162777573
  'y': 976.2868357773948
  z: -519.1469741516394
camera_rotate:
  x: -2.211661501528204
  'y': 0.005560582655216776
  z: 3.13413786140283
camera_target:
  x: 18.158772146296723
  'y': 48.89059850564385
  z: 172.5881135855753
style: 'width: 1100px; height: 500px'
entities:
  - entity: light.sala_smart_b1
    object_id: Lampada1_2
    type3d: light
    light:
      lumens: '800'
      color: yellow
  - entity: light.sala_smart_b2
    object_id: Lampada2_2
    type3d: light
    light:
      color: blue
      lumens: '800'
  - entity: light.sala_smart_b3
    object_id: Lampada3_2
    type3d: light
    light:
      color: white
      lumens: '800'
  - entity: light.sala_smart_b4
    object_id: Lampada4_2
    type3d: light
    light:
      color: red
      lumens: '800'
  - entity: light.sala_smart_b5
    object_id: Lampada5_2
    type3d: light
    light:
      color: purple
      lumens: '800'
shadow: 'no'                                  ### --> If YES stop automatically,  if NO work a little longer, but in the end it freezes too.###
extralightmode: 'no'
globalLightPower: '0.7'
sky: 'no'                              
object_groups:
  - object_group: ''
zoom_areas:
  - zoom: ''
```

**SIMPLE 3D MODEL**

Message Error: "Page Unresponsive (Wait or Exit)"

![PAGINA TRAVA](https://user-images.githubusercontent.com/73760504/162112705-0f331703-ded4-46a8-9c7c-21ee73bc0fd5.jpg)
